# Generated by Django 6.1.1 on 2026-09-07 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('AGRESSIF', 'Agressif'), ('MODERE', 'Modéré'), ('CONSERVATEUR', 'Conservateur')], max_length=16, unique=True)),
                ('label', models.CharField(max_length=32)),
                ('daily_dd', models.FloatField(blank=True, null=True)),
                ('max_dd', models.FloatField(blank=True, null=True)),
                ('plafond_tp', models.FloatField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TradingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('capital', models.FloatField()),
                ('payout_type', models.CharField(choices=[('ON_DEMAND', 'On-Demand'), ('DEUX_SEMAINES', '2 Semaines'), ('UN_MOIS', '1 Mois')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('risk_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='performance.riskprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_vr', models.PositiveSmallIntegerField()),
                ('score_ep', models.PositiveSmallIntegerField()),
                ('score_vp', models.PositiveSmallIntegerField()),
                ('score_total', models.PositiveSmallIntegerField()),
                ('risk_reward', models.FloatField(blank=True, null=True)),
                ('pnl', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('EN_COURS', 'En cours'), ('CLOTURE', 'Clôturé'), ('VERROUILLE', 'Verrouillé')], default='EN_COURS', max_length=16)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='performance.tradingaccount')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
    ]
