# Generated by Django 6.1.1 on 2026-10-05 18:52

from django.db import migrations, models


def dedupe_open_trades(apps, schema_editor):
    """Pre-fix for accounts that somehow ended up with more than one
    EN_COURS trade before this constraint existed (the bug this migration
    fixes). Keeps the most recently opened trade EN_COURS on each account
    and marks any older duplicates VERROUILLE, so AddConstraint below never
    fails on existing data."""
    Trade = apps.get_model('performance', 'Trade')
    from django.db.models import Count

    duplicated_accounts = (
        Trade.objects.filter(status='EN_COURS')
        .values('account')
        .annotate(n=Count('id'))
        .filter(n__gt=1)
        .values_list('account', flat=True)
    )
    for account_id in duplicated_accounts:
        trades = list(Trade.objects.filter(account_id=account_id, status='EN_COURS').order_by('-opened_at'))
        for stale in trades[1:]:
            stale.status = 'VERROUILLE'
            stale.save(update_fields=['status'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_tradingaccount_current_balance'),
    ]

    operations = [
        migrations.RunPython(dedupe_open_trades, noop),
        migrations.AddConstraint(
            model_name='trade',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'EN_COURS')), fields=('account',), name='one_open_trade_per_account'),
        ),
    ]
