# Generated by Django 6.1.1 on 2026-10-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0004_trade_one_open_trade_per_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='close_reason',
            field=models.CharField(blank=True, choices=[('logged', 'Logged'), ('take_profit_forced', 'Take-profit forced'), ('daily_drawdown', 'Daily drawdown'), ('max_drawdown', 'Max drawdown')], max_length=32, null=True),
        ),
    ]
