# Generated by Django 6.1.1 on 2026-09-07 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('psych', 'Psych'), ('tech', 'Tech')], max_length=8)),
                ('weight_in_gate', models.FloatField(default=0.2)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GateAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'in_progress'), ('passed', 'passed'), ('locked', 'locked')], default='in_progress', max_length=16)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CriterionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('validated', models.BooleanField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gate.criterion')),
                ('gate_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_results', to='gate.gateattempt')),
            ],
            options={
                'unique_together': {('gate_attempt', 'criterion')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('text', models.CharField(max_length=255)),
                ('weight', models.FloatField(default=0.16666666666666666)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='gate.criterion')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('criterion', 'order')},
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('criterion_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='gate.criterionresult')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gate.question')),
            ],
            options={
                'unique_together': {('criterion_result', 'question')},
            },
        ),
    ]
