# Generated by Django 6.1.1 on 2026-10-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0002_seed_criteria_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='positive_answer',
            field=models.BooleanField(default=True),
        ),
    ]
