# Generated by Django 6.1.1 on 2026-10-05 18:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0004_reverse_phrase_one_question_per_criterion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gateattempt',
            index=models.Index(fields=['user', '-started_at'], name='gate_gateat_user_id_866d9c_idx'),
        ),
    ]
